ALTER TABLE t_sites 
ALTER COLUMN site_no DROP DEFAULT;

ALTER TABLE t_sites 
ALTER COLUMN site_no ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
  pg_get_serial_sequence('t_sites', 'site_no'), 
  COALESCE((SELECT MAX(site_no) FROM t_sites), 0) + 1, 
  false
);